package com.example.bwa.user;

import lombok.*;

import javax.persistence.*;
import javax.validation.constraints.NotBlank;
import java.util.List;

@NoArgsConstructor
@AllArgsConstructor
@Getter
@Setter
@ToString
@EqualsAndHashCode
@Entity
@Table
public class Favourite {
    @Id
    @SequenceGenerator(
            name = "f_sequence",
            sequenceName = "f_sequence",
            allocationSize = 1
    )
    @GeneratedValue(
            strategy = GenerationType.SEQUENCE,
            generator = "f_sequence"
    )
    @Column(nullable = false, updatable = false) //WE DON'T SEND id AT POST REQUEST: id - GENERATED BY @GeneratedValue
    private @NotBlank Long fId;
    @OneToOne(mappedBy = "favourite")
    private User user;
    @OneToMany(mappedBy = "favourite", cascade = CascadeType.ALL)
    private List<Book> books;
}
