package com.example.bwa.user;

import com.example.bwa.enums.UserType;
import lombok.*;

import javax.persistence.*;
import javax.validation.constraints.NotBlank;
import java.util.List;

@NoArgsConstructor
@AllArgsConstructor
@Getter
@Setter
@ToString
@EqualsAndHashCode
@Entity
@Table(name = "user")
public class User {

    @Id
    @SequenceGenerator(
            name = "user_sequence",
            sequenceName = "user_sequence",
            allocationSize = 1
    )
    @GeneratedValue(
            strategy = GenerationType.SEQUENCE,
            generator = "user_sequence"
    )
    @Column(nullable = false, updatable = false) //WE DON'T SEND id AT POST REQUEST: id - GENERATED BY @GeneratedValue
    private Long userId;
    private String username;
    private String password;
    private String email;
    private UserType userType;
    private Boolean logged;
    @OneToMany(mappedBy = "user", cascade = CascadeType.ALL)
    private List<Book> writtenBooks; //cartile scrise de scriitor!!! pt cititor va fi null
    @OneToOne(cascade = CascadeType.ALL)
    @JoinColumn(name = "w_id"/*, referencedColumnName = "userId"*/)
    private Wishlist wishlist;
    @OneToOne(cascade = CascadeType.ALL)
    @JoinColumn(name = "f_id"/*, referencedColumnName = "userId"*/)
    private Favourite favourite;

}
